# Generated by Django 2.0.4 on 2018-04-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(verbose_name='create time')),
            ],
        ),
    ]
